//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetDimension.NanUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetDimension.NanUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///	const ATTR_NAME = &quot;n-ui-command&quot;;
        ///
        ///	if (!window[&quot;raiseCustomEvent&quot;]) {
        ///		window[&quot;raiseCustomEvent&quot;] = function (eventName, customDetail) {
        ///			window.dispatchEvent(new CustomEvent(eventName, { detail: customDetail }));
        ///		};
        ///	}
        ///
        ///	
        ///	document.addEventListener(&quot;click&quot;, (e) =&gt; {
        ///		var targetEl = e.srcElement;
        ///
        ///		while (targetEl &amp;&amp; !targetEl.hasAttribute(ATTR_NAME)) {
        ///			targetEl = targetEl.parentElement;
        ///		}
        ///
        ///		if (targetEl) {
        ///			var cmd = targetEl.getAttribute(ATTR_NAME);
        ///
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nanui_frameGlobal {
            get {
                return ResourceManager.GetString("nanui_frameGlobal", resourceCulture);
            }
        }
    }
}
